# Generated by Django 3.1.4 on 2021-03-14 09:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.EmailField(default=None, max_length=254)),
                ('outletname', models.CharField(max_length=30)),
                ('foodtype', models.CharField(max_length=20)),
                ('homedelivery', models.CharField(default='No', max_length=5)),
                ('ownerfirstname', models.CharField(max_length=20)),
                ('ownerlastname', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('addresslink', models.URLField()),
                ('iframeaddress', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='outlets/')),
            ],
        ),
    ]
