# Generated by Django 3.1.7 on 2021-03-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='user',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='outlets/'),
        ),
    ]
