# Generated by Django 3.1.4 on 2021-03-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210314_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='desc',
        ),
    ]
