# Generated by Django 3.1.4 on 2021-03-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210314_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='desc',
            new_name='message',
        ),
    ]
