# Generated by Django 3.1.4 on 2021-03-14 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20210314_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 16, 4, 46, 66322)),
        ),
    ]
